# Generated by Django 2.0.6 on 2018-06-13 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200)),
                ('slug', models.SlugField(default=None, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated')),
                ('tags', models.ManyToManyField(to='taggit.Tag')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['-created'],
                'get_latest_by': ['-created'],
            },
        ),
    ]
