# Generated by Django 2.0.6 on 2018-06-28 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_topic_parenttopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='elastic_search_query_dsl',
        ),
    ]
