version: '3.3'

services:

  postgres:
    container_name: postgres
    hostname: postgres
    restart: on-failure
    image: postgres:alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:5432:5432"

  web:
    container_name: web
    hostname: web
    restart: always
    build: ./web
    volumes:
      - ./web:/opt/vtalks/web/
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  pgdata:
