source_urls = {
    "2014": [
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2014/javascript.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2014/ruby.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2014/ux.json",
    ],
    "2015": [
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2015/ruby.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2015/ux.json",
    ],
    "2016": [
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2016/ruby.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2016/ux.json",
    ],
    "2017": [
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2017/javascript.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2017/android.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2017/css.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2017/data.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2017/devops.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2017/general.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2017/ios.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2017/php.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2017/ruby.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2017/tech-comm.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2017/ux.json",
    ],
    "2018": [
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2018/javascript.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2018/android.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2018/css.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2018/data.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2018/devops.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2018/dotnet.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2018/elixir.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2018/general.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2018/golang.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2018/ios.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2018/php.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2018/python.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2018/ruby.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2018/rust.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2018/scala.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2018/security.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2018/tech-comm.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2018/ux.json",
    ],
    "2019": [
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2019/javascript.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2019/android.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2019/css.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2019/data.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2019/devops.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2019/elixir.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2019/general.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2019/golang.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2019/ios.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2019/php.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2019/python.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2019/ruby.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2019/rust.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2019/security.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2019/tech-comm.json",
        "https://raw.githubusercontent.com/tech-conferences/conference-data/master/conferences/2019/ux.json",
    ]
}

source_urls_javascript = {

}
