version: 2
jobs:
  web:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
      - run:
          command: |
            . .venv/bin/activate
            cd web
            make cover
  crawler:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
      - run:
          command: |
            . .venv/bin/activate
            cd crawler
            echo "test crawler"
workflows:
  version: 2
  web_and_crawler:
    jobs:
      - web
      - crawler