version: 2
jobs:

  # Web project
  web_test:
    docker:
      - image: circleci/python:latest
    environment:
      - COVERALLS_REPO_TOKEN: "9c7WYblg4HhL8IjFh4nkQcy2GawPvu5qy"
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: |
            . .venv/bin/activate
            cd web
            python manage.py test --settings=settings.test
            coverage run manage.py test --settings=settings.test
            coveralls

workflows:
  version: 2
  web:
    jobs:
      - web_test
