version: 2
jobs:

  # Web project
  web_test:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          command: |
            docker-compose

workflows:
  version: 2
  web:
    jobs:
      - web_test
