version: 2
jobs:
   build:
     docker:
       - image: circleci/python:latest
     steps:
       - checkout
       - run:
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -r web/requirements.txt
       - run:
          command: |
            cd web && make test