version: 2
jobs:

  # Web project
  web_test:
    docker:
      - image: circleci/python:latest
      - image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
      - image: nats:latest
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: |
            . .venv/bin/activate
            cd web
            # python manage.py test --settings=settings.test
            # coverage run manage.py test --settings=settings.test
            codecov

  # Docker build
  docker_build:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            make docker-build

  # Docker publish
  docker_publish:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            make docker-build
      - run:
          command: |
            docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
      - run:
          command: |
            make docker-publish

workflows:
  version: 2
  
  web:
    jobs:
      - web_test
      - docker_build
      - docker_publish
