version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            cd web
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "web/requirements.txt" }}
          paths:
            - ".venv"
      - run:
          command: |
            . .venv/bin/activate
            cd web
            make cover