version: 2
jobs:

  # Web project
  web_test:
    docker:
      - image: circleci/python:latest
      - image: docker.elastic.co/elasticsearch/elasticsearch-oss:latest
        ports:
          - "9200:9200"
      - image: nats:latest
        ports:
          - "4222:4222"
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: |
            . .venv/bin/activate
            cd web
            # python manage.py test --settings=settings.test
            # coverage run manage.py test --settings=settings.test
            codecov

  # Docker build
  docker_build:
    machine: true
    steps:
      - setup_remote_docker
      - checkout
      - run:
          command: |
            python3 -m venv .venv
      - run:
          command: |
            . .venv/bin/activate
            make docker-build

  # Docker publish
  docker_publish:
    machine: true
    steps:
      - setup_remote_docker
      - checkout
      - run:
          command: |
            python3 -m venv .venv
      - run:
          command: |
            . .venv/bin/activate
            make docker-build
      - run:
          command: |
            . .venv/bin/activate
            make docker-publish

workflows:
  version: 2
  web:
    jobs:
      - web_test
      - docker_build
      - docker_publish
