version: 2
jobs:

  # Web project
  web_test:
    docker:
      - image: circleci/python:latest
      - image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: |
            . .venv/bin/activate
            cd web
            python manage.py test --settings=settings.test
            # coverage run manage.py test --settings=settings.test
            codecov

workflows:
  version: 2
  web:
    jobs:
      - web_test
