version: 2
jobs:
  build:
    working_directory: ~/vtalks.net/web
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            cd web
            pip install -r requirements.txt
            make cover