version: 2
jobs:
   build:
     docker:
       - image: circleci/python:latest
     steps:
       - checkout
       - run:
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            cd web
            sudo pip install -r requirements.txt
       - run:
          command: |
            . .venv/bin/activate
            cd web
            make test
            make cover