# Generated by Django 2.0 on 2017-12-17 11:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, max_length=25, unique=True)),
                ('title', models.CharField(default=None, max_length=200)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('tags', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('viewCount', models.IntegerField(default=0)),
                ('likeCount', models.IntegerField(default=0)),
                ('dislikeCount', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated')),
                ('channel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='channels.Channel')),
                ('playlist', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='playlists.Playlist')),
            ],
            options={
                'verbose_name': 'Talk',
                'verbose_name_plural': 'Talks',
                'ordering': ['-created', '-updated'],
                'get_latest_by': '-created',
            },
        ),
    ]
