# Generated by Django 2.0 on 2017-12-17 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0002_auto_20171217_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='channel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='talks.Channel'),
        ),
    ]
