# Generated by Django 2.0 on 2017-12-10 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0002_talk'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='channel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='talks.Channel'),
        ),
    ]
