# Generated by Django 2.0 on 2017-12-18 16:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0003_auto_20171217_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='code',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='talk',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='talks.Channel'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='code',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='talk',
            name='dislikeCount',
            field=models.IntegerField(default=0, verbose_name='dislike count'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='likeCount',
            field=models.IntegerField(default=0, verbose_name='like count'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='talk',
            name='viewCount',
            field=models.IntegerField(default=0, verbose_name='view count'),
        ),
    ]
