# Generated by Django 2.0 on 2017-12-11 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0003_talk_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='dislikeCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='talk',
            name='favoriteCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='talk',
            name='likeCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='talk',
            name='viewCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='channel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 16, 39, 23, 569533), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 16, 39, 23, 569564), verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 16, 39, 23, 570260), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 16, 39, 23, 570285), verbose_name='date updated'),
        ),
    ]
