# Generated by Django 2.0 on 2017-12-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0004_auto_20171218_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
