# Generated by Django 2.0 on 2017-12-18 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0005_auto_20171218_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='dislikeCount',
            new_name='dislike_count',
        ),
        migrations.RenameField(
            model_name='talk',
            old_name='likeCount',
            new_name='like_count',
        ),
        migrations.RenameField(
            model_name='talk',
            old_name='viewCount',
            new_name='view_count',
        ),
    ]
