# Generated by Django 2.0 on 2017-12-22 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0006_auto_20171219_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='tags',
            new_name='tags_old',
        ),
    ]
