# Generated by Django 2.0 on 2017-12-11 16:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0006_auto_20171211_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 16, 43, 29, 304572, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 16, 43, 29, 304610, tzinfo=utc), verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 16, 43, 29, 305238, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 16, 43, 29, 305264, tzinfo=utc), verbose_name='date updated'),
        ),
    ]
