# Generated by Django 2.0 on 2017-12-22 09:13

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('talks', '0007_auto_20171222_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
