# Generated by Django 2.0 on 2017-12-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0008_talk_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='tags_old',
        ),
    ]
