# Generated by Django 2.0 on 2017-12-11 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0008_auto_20171211_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='description',
        ),
    ]
