# Generated by Django 2.0 on 2017-12-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0009_remove_talk_tags_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='code',
            field=models.CharField(default=None, max_length=25, unique=True),
        ),
    ]
