# Generated by Django 2.0 on 2017-12-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0009_remove_channel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='tags',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
