# Generated by Django 2.0 on 2017-12-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0009_remove_talk_tags_old'),
    ]

    operations = [

    ]
