# Generated by Django 2.0 on 2017-12-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0010_talk_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='tags',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
