# Generated by Django 2.0 on 2017-12-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0010_auto_20171222_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='code',
            field=models.CharField(default=None, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='talk',
            name='slug',
            field=models.SlugField(default=None, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='talk',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
