# Generated by Django 2.0 on 2017-12-22 22:46

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0011_auto_20171222_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
