# Generated by Django 2.0 on 2017-12-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0012_auto_20171222_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='slug',
            field=models.TextField(default=None, max_length=200, null=True),
        ),
    ]
