# Generated by Django 2.0 on 2017-12-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0012_auto_20171212_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='favoriteCount',
        ),
    ]
