# Generated by Django 2.0 on 2017-12-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0013_remove_talk_favoritecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
