# Generated by Django 2.0 on 2017-12-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0013_channel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
