# Generated by Django 2.0 on 2017-12-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0014_auto_20171226_2212'),
    ]

    operations = [

    ]
