# Generated by Django 2.0 on 2017-12-28 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0015_auto_20171226_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
