# Generated by Django 2.0 on 2017-12-29 21:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0016_talk_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='playlist',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='playlists.Playlist'),
        ),
    ]
