# Generated by Django 2.0 on 2017-12-30 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0017_auto_20171229_2159'),
    ]

    operations = [

    ]
