# Generated by Django 2.0 on 2018-01-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0018_remove_playlist_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='wilsonscore_rank',
            field=models.FloatField(default=0, verbose_name='wilson score rank'),
        ),
    ]
