# Generated by Django 2.0.1 on 2018-01-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0021_talk_hacker_hot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='dislike_count',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='view_count',
        ),
        migrations.AddField(
            model_name='talk',
            name='youtube_dislike_count',
            field=models.IntegerField(default=0, verbose_name='youtube dislike count'),
        ),
        migrations.AddField(
            model_name='talk',
            name='youtube_like_count',
            field=models.IntegerField(default=0, verbose_name='youtube like count'),
        ),
        migrations.AddField(
            model_name='talk',
            name='youtube_view_count',
            field=models.IntegerField(default=0, verbose_name='youtube view count'),
        ),
    ]
