# Generated by Django 2.0.1 on 2018-01-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0023_talk_youtube_favorite_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='dislike_count',
            field=models.IntegerField(default=0, verbose_name='dislike count'),
        ),
        migrations.AddField(
            model_name='talk',
            name='favorite_count',
            field=models.IntegerField(default=0, verbose_name='favorite count'),
        ),
        migrations.AddField(
            model_name='talk',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='like count'),
        ),
        migrations.AddField(
            model_name='talk',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='view count'),
        ),
    ]
