# Generated by Django 2.0.1 on 2018-01-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0024_auto_20180114_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(max_length=200, blank=True, null=True),
        ),
    ]
