# Generated by Django 2.0.1 on 2018-01-16 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0025_playlist_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'get_latest_by': ['-created'], 'ordering': ['-created'], 'verbose_name': 'Channel', 'verbose_name_plural': 'Channels'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'get_latest_by': ['-created'], 'ordering': ['-created'], 'verbose_name': 'Playlist', 'verbose_name_plural': 'Playlists'},
        ),
        migrations.AlterModelOptions(
            name='talk',
            options={'get_latest_by': '-created', 'ordering': ['-created'], 'verbose_name': 'Talk', 'verbose_name_plural': 'Talks'},
        ),
    ]
