# Generated by Django 2.0.1 on 2018-01-24 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talks', '0026_auto_20180116_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('talk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='talks.Talk')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Talk Like',
                'verbose_name_plural': 'Talks Likes',
                'ordering': ['-created'],
                'get_latest_by': '-created',
            },
        ),
    ]
