# Generated by Django 2.0.1 on 2018-02-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0031_auto_20180206_0936'),
        ('talks', '0031_auto_20180206_0938'),
        ('talks', '0031_auto_20180206_0933'),
    ]

    operations = [
    ]
