# Generated by Django 2.0.2 on 2018-02-23 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0033_auto_20180217_1239'),
    ]

    operations = [

    ]
