# Generated by Django 2.0.6 on 2018-06-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0035_auto_20180602_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='published',
            field=models.BooleanField(default=True, verbose_name='is published'),
        ),
    ]
