# Generated by Django 2.0.2 on 2018-02-23 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, max_length=100, unique=True)),
                ('title', models.CharField(default=None, max_length=200)),
                ('slug', models.SlugField(default=None, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated')),
            ],
            options={
                'verbose_name': 'Playlists',
                'verbose_name_plural': 'Playlists',
                'ordering': ['-created'],
                'get_latest_by': ['-created'],
            },
        ),
    ]
