# Generated by Django 2.0.6 on 2018-06-30 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('playlists', '0002_auto_20180224_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='channel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='channels.Channel'),
        ),
    ]
