version: '3.3'

services:

  nginx:
    container_name: vtalksnet_nginx
    hostname: nginx
    restart: on-failure
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx.vh.default.conf:/etc/nginx/conf.d/default.conf
      - ../web/static:/static
    ports:
      - "80:80"
    depends_on:
      - web
      - postgres

  postgres:
    container_name: vtalksnet_postgres
    hostname: postgres
    restart: on-failure
    image: postgres:alpine
    ports:
      - "5432:5432"

  web:
    container_name: vtalksnet_web
    hostname: web
    restart: always
    build: ../web
    volumes:
      - ../web:/opt/vtalks/web/
    ports:
      - "8000"
    environment:
      - TWITTER_TOKEN
      - TWITTER_SECRET
      - YOUTUBE_API_KEY
    depends_on:
      - postgres