# Generated by Django 2.0 on 2017-12-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20171217_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='oauth_token',
            field=models.CharField(blank=True, max_length=100, verbose_name='OAuth Token'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='oauth_token_secret',
            field=models.CharField(blank=True, max_length=100, verbose_name='OAuth2 Token Secret'),
        ),
    ]
