# Generated by Django 2.0.1 on 2018-01-16 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20180116_0340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'get_latest_by': ['-user__date_joined'], 'ordering': ['-user__date_joined'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
