# Generated by Django 2.0.1 on 2018-01-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180130_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='event_end',
            field=models.DateField(blank=True, null=True, verbose_name='end'),
        ),
        migrations.AddField(
            model_name='edition',
            name='event_start',
            field=models.DateField(blank=True, null=True, verbose_name='start'),
        ),
    ]
