# Generated by Django 2.0.1 on 2018-01-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180130_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='venue',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
