# Generated by Django 2.0.6 on 2018-06-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_edition_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='twitter',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
